# Generated by Django 3.1.3 on 2021-01-11 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210108_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 0, 43, 56, 325141)),
        ),
    ]
