# Generated by Django 3.1.5 on 2021-02-07 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210111_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 38, 56, 497374)),
        ),
    ]
