# Generated by Django 3.1.5 on 2021-02-10 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210207_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 17, 29, 25, 540678)),
        ),
    ]
