# Generated by Django 3.1.5 on 2021-02-10 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210210_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 17, 54, 14, 340110)),
        ),
    ]
