# Generated by Django 3.1.5 on 2021-02-10 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210210_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 19, 57, 39, 740637)),
        ),
    ]
